version: "3.9"
services:
  client:
    build:
      context: ./client
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./client:/code
    links:
      - server
  server:
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./server:/code
    environment:
      - chatApp_db_uri=mongodb://mongo:27017
      - chatApp_redis_uri=redis://redis:6379
    links:
      - mongo
      - redis
  mongo:
    image: mongo:4.4.6
    logging:
      driver: none
    ports:
      - 27017:27017
    volumes:
      - /var/lib/mongodb:/data/db
  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
